### ISSUE TITLE
Focus on services rather than tools

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/related-tooling#1]
Right now, the list lists "tools" with a mix bag of actual tools and services/servers.

I don't necessarily think we need a new list of tools (there is already quite a few of those outthere, and there is discussion in the SpecEd CG to create a better maintenance story for such a list)

What I do think we need is a clear list of services (~ HTTP URLs) that are used for W3C work but not operated by W3C systems but by members of our community. In particular, it's not obvious that a link to an underlying github repo is in general relevant.

I'm not sure we need to list all the subdomains and paths in a given domains (e.g. *.csswg.org) , unless they correspond to different ownership.

**Comment by deniak** [comment]
Fair enough. Listing the tools would indeed compete with the CG which will probably do a better job.
Regarding the link to the repo, I'm actually hoping the owners would provide some details, in this repo or the service repo, on how we can rebuild the service if something happens so having the link could be handy.
